name: implementing-ci-pipeline
run-name: ${{ github.actor }} is implementing CI-CD in the pipeline

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Install dependencies with requirements.txt
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test with pytest
              run: pytest tests/test_contrato.py
